# Generated by Django 4.0 on 2022-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='addedToCartAt',
        ),
        migrations.AddField(
            model_name='product',
            name='unitSold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
