# Generated by Django 4.0.3 on 2022-03-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_height_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='address',
            new_name='address1',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='postalCode',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='shippingPrice',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
