# Generated by Django 4.0.3 on 2022-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_address_shippingdetails_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
