# Generated by Django 4.0.3 on 2022-03-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_shippingdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
    ]
