# Generated by Django 4.0.3 on 2022-03-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
