# Generated by Django 4.0.3 on 2022-03-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
