# Generated by Django 4.0.3 on 2022-03-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_qty_orderitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='totalAmount',
        ),
    ]
